config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }
  resources :posts do
    resources :comments
  end
  root "posts#index"
  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 4 }
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:create, :destroy]
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def set_comment
    @post = Post.find(params[:post_id])
  end
  def comment_params
    params.require(:comment).permit(:name, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def show
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = t('posts.created')
      redirect_to @post
    else
      flash[:danger] = t('posts.failed')
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = t('posts.updated')
      redirect_to @post
    else
      flash[:danger] = t('posts.failed')
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment_clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>
  <% if user_signed_in? %>
    <p><%= link_to 'Delete', [comment.post, comment],
                  method: :delete,
                  class: 'button',
                  data: { confirm: 'Are you sure?' } %></p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{name}") %>
    <% end %>
    <div id="sidebar">
      <div id="logo">
        <%= link_to root_path do %>
          <%= image_tag "logo.svg" %>
        <% end %>
      </div>
      <ul>
        <li class="category">Website</li>
        <li><%= link_to "Blog", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      <ul>
        <li class="category">Social</li>
        <li><a href="https://twitter.com/KChivorn">Twitter</a></li>
        <li><a href="https://github.com/kchivorn">Github</a></li>
        <li><a href="https://facebook.com/KuochChivorn">Facebook</a></li>
        <li><a href="mailto:kouch.chivorn@gmail.com">Email</a></li>
      </ul>
      <% if user_signed_in? %>
        <div class="sign_in">Admin Login</div>
      <% end %>
    </div>
    <div id="main_content">
      <div id="header">
        <% if current_page?(root_path) %>
          <p>All Posts</p>
        <% elsif current_page?(about_path) %>
          <p>About</p>
        <% else %>
          <%= link_to "Back to All Posts", root_path %>
        <% end %>
        <div class="buttons">
          <% if user_signed_in? %>
            <button class="button"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></button>
            <button class="button"><%= link_to "New Post", new_post_path %></button>
          <% else %>
            <button class="button"><%= link_to "Login", new_user_session_path %></button>
          <% end %>

        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag 'profile.jpg' %>
  </div>
  <div id="content">
    <h1>Hi, I'm Chivorn Kouch</h1>
    <p>I am reviewing my skills by buildings some small projects.</p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %> <br>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post_wrapper">
  <h2 class="title">
    <%= link_to post.title, post %>
  </h2>
  <p class="date"><small>Submitted on <%= post.created_at.strftime("%B, %d, %Y") %> </small></p>
  <p class="body"><%= post.body %></p>
</div>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<%= render @posts %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>Create New Post</h1>
  <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= f.label :title %> <br>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :body %> <br>
      <%= f.text_area :body %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  <% end %>
</div>

  

app/views/posts/show.html.erb
<div id="post_content">
  <h1><%= @post.title %></h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
    <% if user_signed_in? %>
      | <%= link_to 'Edit', edit_post_path(@post) %>
      | <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>

  <p class="body"><%= @post.body %></p>
  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
    <h3>Add a comment:</h3>
    <%= render 'comments/form' %>
  </div>
</div>